# Generated by Django 2.2.4 on 2019-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0002_auto_20190515_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='num_doc',
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='output'),
        ),
        migrations.AddField(
            model_name='documento',
            name='email',
            field=models.EmailField(default='josircg@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='nome',
            field=models.CharField(default='Josir', max_length=60, verbose_name='Nome do pesquisador'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
