# Generated by Django 2.2.4 on 2019-09-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0003_auto_20190913_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='language',
            field=models.CharField(default='pt-br', max_length=5, verbose_name='Linguagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='output', verbose_name='Arquivo em PDF ou Texto'),
        ),
    ]
