# Generated by Django 2.2.4 on 2019-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0004_auto_20190915_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default='1', upload_to='output', verbose_name='Arquivo em PDF ou Texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Linguagem'),
        ),
    ]
