# Generated by Django 2.2.4 on 2019-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0005_auto_20190915_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='titulo',
            field=models.TextField(blank=True, null=True, verbose_name='Título do artigo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(max_length=200, upload_to='output', verbose_name='Arquivo em PDF ou Texto'),
        ),
    ]
