# Generated by Django 2.2.14 on 2020-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0007_auto_20200728_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='documento',
            name='descritivo',
            field=models.TextField(blank=True, null=True, verbose_name='Descritivo da Nuvem'),
        ),
        migrations.AddField(
            model_name='documento',
            name='imagem',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='modelo', verbose_name='Imagem Modelo'),
        ),
    ]
