# Generated by Django 2.2.14 on 2020-07-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0008_auto_20200729_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='chave',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Chave de Acesso'),
        ),
    ]
