# Generated by Django 2.2.14 on 2021-04-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0010_documento_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='stopwords',
            field=models.TextField(blank=True, null=True, verbose_name='Stopwords Extras'),
        ),
    ]
